uint8 type #EXECUTE RECORD LOAD_TRAFFIC_ROUTE QR_NAV
#执行任务
uint8 EXECUTE = 0
#记录路径
uint8 RECORD = 1

uint8 command #START PAUSE STOP KEEP_TEACH KEEP_COVER DISCARD KEEP_TRAFFIC_ROUTE

#开始任务
uint8 START = 0
#暂停任务
uint8 PAUSE = 1
#停止任务
uint8 STOP = 2


#目录
string dir
#路径名称
string path_name
#地图名称
string map
---
#消息
string message
